/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.grupo.unidaddered.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.grupo.unidaddered.logic.dto.UnidadDeRedDTO;
import co.edu.uniandes.csw.grupo.unidaddered.logic.api.IUnidadDeRedLogicService;
import co.edu.uniandes.csw.grupo.unidaddered.master.logic.api._IUnidadDeRedMasterLogicService;
import co.edu.uniandes.csw.grupo.unidaddered.master.logic.dto.UnidadDeRedMasterDTO;
import co.edu.uniandes.csw.grupo.problema.logic.api.IProblemaLogicService;
import co.edu.uniandes.csw.grupo.usuariounidaddered.logic.api.IUsuarioUnidadDeRedLogicService;
import co.edu.uniandes.csw.grupo.problema.logic.dto.ProblemaDTO;
import co.edu.uniandes.csw.grupo.usuariounidaddered.logic.dto.UsuarioUnidadDeRedDTO;
import javax.inject.Inject;


public abstract class _UnidadDeRedMasterMockLogicService implements _IUnidadDeRedMasterLogicService {

    protected static ArrayList<UnidadDeRedMasterDTO> unidadDeRedMasterDtosList = new ArrayList<UnidadDeRedMasterDTO>() ;
    @Inject
    protected IProblemaLogicService problemaPersistance;
    @Inject
    protected IUsuarioUnidadDeRedLogicService usuarioUnidadDeRedPersistance;
    @Inject
    protected IUnidadDeRedLogicService unidadDeRedPersistance;

    public UnidadDeRedMasterDTO createMasterUnidadDeRed(UnidadDeRedMasterDTO unidadDeRed) {

        unidadDeRedPersistance.createUnidadDeRed(unidadDeRed.getUnidadDeRedEntity());
        for (UsuarioUnidadDeRedDTO dto : unidadDeRed.getCreateusuarios()) {
            usuarioUnidadDeRedPersistance.createUsuarioUnidadDeRed(dto);
        }
        for (ProblemaDTO dto : unidadDeRed.getCreateproblemas()) {
            problemaPersistance.createProblema(dto);
        }
        unidadDeRedMasterDtosList.add(unidadDeRed);
        return unidadDeRed;
    }

    public UnidadDeRedMasterDTO getMasterUnidadDeRed(Long id) {
        for (UnidadDeRedMasterDTO unidadDeRedMasterDTO : unidadDeRedMasterDtosList) {
            if (unidadDeRedMasterDTO.getUnidadDeRedEntity().getId() == id) {
                return unidadDeRedMasterDTO;
            }
        }

        return null;
    }

    public void deleteMasterUnidadDeRed(Long id) {
        for (UnidadDeRedMasterDTO unidadDeRedMasterDTO : unidadDeRedMasterDtosList) {
            if (unidadDeRedMasterDTO.getUnidadDeRedEntity().getId() == id) {

                for (UsuarioUnidadDeRedDTO dto : unidadDeRedMasterDTO.getCreateusuarios()) {
                    usuarioUnidadDeRedPersistance.deleteUsuarioUnidadDeRed(dto.getId());
                }
                unidadDeRedPersistance.deleteUnidadDeRed(unidadDeRedMasterDTO.getId());
                unidadDeRedMasterDtosList.remove(unidadDeRedMasterDTO);
                for (ProblemaDTO dto : unidadDeRedMasterDTO.getCreateproblemas()) {
                    problemaPersistance.deleteProblema(dto.getId());
                }
                unidadDeRedPersistance.deleteUnidadDeRed(unidadDeRedMasterDTO.getId());
                unidadDeRedMasterDtosList.remove(unidadDeRedMasterDTO);
            }
        }

    }

    public void updateMasterUnidadDeRed(UnidadDeRedMasterDTO unidadDeRed) {

        // update UsuarioUnidadDeRed
        if (unidadDeRed.getUpdateusuarios() != null) {
            for (UsuarioUnidadDeRedDTO dto : unidadDeRed.getUpdateusuarios()) {
                usuarioUnidadDeRedPersistance.updateUsuarioUnidadDeRed(dto);
            }
        }
        // persist new UsuarioUnidadDeRed
        if (unidadDeRed.getCreateusuarios() != null) {
            for (UsuarioUnidadDeRedDTO dto : unidadDeRed.getCreateusuarios()) {
                UsuarioUnidadDeRedDTO persistedUsuarioUnidadDeRedDTO = usuarioUnidadDeRedPersistance.createUsuarioUnidadDeRed(dto);
                dto = persistedUsuarioUnidadDeRedDTO;
            }
        }
        // delete UsuarioUnidadDeRed
        if (unidadDeRed.getDeleteusuarios() != null) {
            for (UsuarioUnidadDeRedDTO dto : unidadDeRed.getDeleteusuarios()) {

                usuarioUnidadDeRedPersistance.deleteUsuarioUnidadDeRed(dto.getId());
            }
        }
        // update Problema
        if (unidadDeRed.getUpdateproblemas() != null) {
            for (ProblemaDTO dto : unidadDeRed.getUpdateproblemas()) {
                problemaPersistance.updateProblema(dto);
            }
        }
        // persist new Problema
        if (unidadDeRed.getCreateproblemas() != null) {
            for (ProblemaDTO dto : unidadDeRed.getCreateproblemas()) {
                ProblemaDTO persistedProblemaDTO = problemaPersistance.createProblema(dto);
                dto = persistedProblemaDTO;
            }
        }
        // delete Problema
        if (unidadDeRed.getDeleteproblemas() != null) {
            for (ProblemaDTO dto : unidadDeRed.getDeleteproblemas()) {

                problemaPersistance.deleteProblema(dto.getId());
            }
        }
    }
}