/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.grupo.paginaweb.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.grupo.paginaweb.logic.dto.PaginaWebDTO;
import co.edu.uniandes.csw.grupo.paginaweb.persistence.api._IPaginaWebPersistence;
import co.edu.uniandes.csw.grupo.paginaweb.persistence.converter.PaginaWebConverter;
import co.edu.uniandes.csw.grupo.paginaweb.persistence.entity.PaginaWebEntity;

public abstract class _PaginaWebPersistence implements _IPaginaWebPersistence {

  	@PersistenceContext(unitName="RigitalVerPU")
 
	protected EntityManager entityManager;
	
	public PaginaWebDTO createPaginaWeb(PaginaWebDTO paginaWeb) {
		PaginaWebEntity entity=PaginaWebConverter.persistenceDTO2Entity(paginaWeb);
		entityManager.persist(entity);
		return PaginaWebConverter.entity2PersistenceDTO(entity);
	}

	@SuppressWarnings("unchecked")
	public List<PaginaWebDTO> getPaginaWebs() {
		Query q = entityManager.createQuery("select u from PaginaWebEntity u");
		return PaginaWebConverter.entity2PersistenceDTOList(q.getResultList());
	}

	public PaginaWebDTO getPaginaWeb(Long id) {
		return PaginaWebConverter.entity2PersistenceDTO(entityManager.find(PaginaWebEntity.class, id));
	}

	public void deletePaginaWeb(Long id) {
		PaginaWebEntity entity=entityManager.find(PaginaWebEntity.class, id);
		entityManager.remove(entity);
	}

	public void updatePaginaWeb(PaginaWebDTO detail) {
		PaginaWebEntity entity=entityManager.merge(PaginaWebConverter.persistenceDTO2Entity(detail));
		PaginaWebConverter.entity2PersistenceDTO(entity);
	}

}