/* ========================================================================
 * Copyright 2014 grupo
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.grupo.usuarioexternorepo.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.grupo.usuarioexternorepo.logic.dto.UsuarioExternoRepoDTO;
import co.edu.uniandes.csw.grupo.usuarioexternorepo.persistence.api._IUsuarioExternoRepoPersistence;
import co.edu.uniandes.csw.grupo.usuarioexternorepo.persistence.converter.UsuarioExternoRepoConverter;
import co.edu.uniandes.csw.grupo.usuarioexternorepo.persistence.entity.UsuarioExternoRepoEntity;

public abstract class _UsuarioExternoRepoPersistence implements _IUsuarioExternoRepoPersistence {

  	@PersistenceContext(unitName="RigitalVerPU")
 
	protected EntityManager entityManager;
	
	public UsuarioExternoRepoDTO createUsuarioExternoRepo(UsuarioExternoRepoDTO usuarioExternoRepo) {
		UsuarioExternoRepoEntity entity=UsuarioExternoRepoConverter.persistenceDTO2Entity(usuarioExternoRepo);
		entityManager.persist(entity);
		return UsuarioExternoRepoConverter.entity2PersistenceDTO(entity);
	}

	@SuppressWarnings("unchecked")
	public List<UsuarioExternoRepoDTO> getUsuarioExternoRepos() {
		Query q = entityManager.createQuery("select u from UsuarioExternoRepoEntity u");
		return UsuarioExternoRepoConverter.entity2PersistenceDTOList(q.getResultList());
	}

	public UsuarioExternoRepoDTO getUsuarioExternoRepo(Long id) {
		return UsuarioExternoRepoConverter.entity2PersistenceDTO(entityManager.find(UsuarioExternoRepoEntity.class, id));
	}

	public void deleteUsuarioExternoRepo(Long id) {
		UsuarioExternoRepoEntity entity=entityManager.find(UsuarioExternoRepoEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateUsuarioExternoRepo(UsuarioExternoRepoDTO detail) {
		UsuarioExternoRepoEntity entity=entityManager.merge(UsuarioExternoRepoConverter.persistenceDTO2Entity(detail));
		UsuarioExternoRepoConverter.entity2PersistenceDTO(entity);
	}

}